name: library_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependency_overrides:
  web: ^0.5.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_screenutil: ^5.9.0
  http: ^1.2.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  zoom_tap_animation: ^1.1.0
  provider: ^6.1.2
  url_launcher: ^6.2.5
  carousel_slider: ^4.2.1
  lottie: ^3.1.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.9
  searchable_listview: ^2.10.2
  flutter_rating_bar: ^4.0.1
  flutter_local_notifications: ^17.0.0
  flutter_timezone: ^1.0.4





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:

    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.otf
        - asset: assets/fonts/inter/Inter-Bold.otf
        - asset: assets/fonts/inter/Inter-Italic.otf
        - asset: assets/fonts/inter/Inter-Light.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-SemiBold.otf


