// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBVbSG_X0AsDU862_BKlNPfVFpM0nVeDE',
    appId: '1:861678833557:web:77ae54619d7a56137db09c',
    messagingSenderId: '861678833557',
    projectId: 'my-auth-e91c2',
    authDomain: 'my-auth-e91c2.firebaseapp.com',
    storageBucket: 'my-auth-e91c2.appspot.com',
    measurementId: 'G-JYS9WLV9JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE2tQqEuFLJy1DUmY9otLkIG2xKU7whpM',
    appId: '1:861678833557:android:db03cf92d199708e7db09c',
    messagingSenderId: '861678833557',
    projectId: 'my-auth-e91c2',
    storageBucket: 'my-auth-e91c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAebxp44PbTwFAWIR_3Q8Q97RTdnJSig',
    appId: '1:861678833557:ios:e85d67451a11ef7e7db09c',
    messagingSenderId: '861678833557',
    projectId: 'my-auth-e91c2',
    storageBucket: 'my-auth-e91c2.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmAebxp44PbTwFAWIR_3Q8Q97RTdnJSig',
    appId: '1:861678833557:ios:cf91c015952359107db09c',
    messagingSenderId: '861678833557',
    projectId: 'my-auth-e91c2',
    storageBucket: 'my-auth-e91c2.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
